//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        public int PostId { get; set; }
        public int UserId { get; set; }
        public string PostTitle { get; set; }
        public string PostTopic { get; set; }
        [DataType(DataType.MultilineText)]
        public string PostDetails { get; set; }
        public System.DateTime PostDateTime { get; set; }
        public Nullable<bool> PostStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
